export const PROJECTS_DATA = [
  {
    _id: 'kanhaji',
    slug: 'kanhaji-japan',
    title: 'Kanhaji Japan',
    subtitle: 'Cross-Border E-Commerce Platform',
    tagline: 'Production-grade e-commerce platform built for a Japan-based client with secure payments, admin management, and scalable cloud architecture.',
    category: 'Freelance',
    techStack: ['Next.js', 'React.js', 'TypeScript', 'Node.js', 'Express.js', 'MongoDB', 'Redis', 'Docker', 'Nginx', 'AWS EC2', 'JWT', 'Tailwind CSS'],
    metrics: [
      { label: 'Status',   value: 'Live 🚀' },
      { label: 'Market',   value: 'Japan 🇯🇵' },
      { label: 'Type',     value: 'Freelance' },
      { label: 'Category', value: 'Full-Stack' },
    ],
    specialBadge: 'Production System',
    demoUrl: 'https://kanhaji.jp',
    githubUrl: '',
    paperUrl: '',
    built: [
      'Engineered a full-stack cross-border e-commerce platform tailored for the Japanese market with modern UI/UX and responsive architecture.',
      'Developed secure authentication and authorization systems, including JWT-based session handling and role-based admin controls.',
      'Integrated payment gateways (GMO & Square), logistics APIs, and automated order workflows.',
      'Built comprehensive admin dashboards for product, order, customer, and inventory management.',
    ],
    engineering: [
      'Implemented Redis caching to reduce repeated database calls and significantly improve API response times.',
      'Configured Nginx reverse proxy for optimized request routing and production-grade deployment.',
      'Containerized all services using Docker for environment consistency and easier horizontal scaling.',
      'Improved SEO and page performance using Next.js SSR/SSG architecture for faster rendering and discoverability in Japanese search results.',
      'Optimized image loading, API calls, and component rendering for a smoother user experience.',
    ],
    impact: [
      'Took end-to-end ownership of the project — from architecture design through deployment and production debugging.',
      'Delivered against real business requirements, balancing scalability, security, and user experience simultaneously.',
      'Managed production deployment, infrastructure setup, and iterative feature cycles independently.',
    ],
    keywords: ['Full Stack Development', 'Production System', 'Scalable Architecture', 'System Design', 'Authentication', 'Performance Optimization', 'Cloud Deployment', 'E-Commerce'],
  },

  {
    _id: 'ai-transcriber',
    slug: 'real-time-ai-transcriber',
    title: 'Real-Time AI Transcriber',
    subtitle: 'Low Latency Speech-to-Text Platform',
    tagline: 'Real-time transcription system capable of converting live speech into editable text with ultra-low latency streaming.',
    category: 'Personal',
    techStack: ['React.js', 'Node.js', 'WebSockets', 'Speech-to-Text API', 'Tailwind CSS'],
    metrics: [
      { label: 'Architecture', value: 'Real-Time' },
      { label: 'Protocol',     value: 'WebSocket' },
      { label: 'Latency',      value: 'Ultra-Low' },
      { label: 'Type',         value: 'Personal' },
    ],
    demoUrl: '',
    githubUrl: '',
    paperUrl: '',
    built: [
      'Developed a real-time speech transcription application capable of processing continuous audio streams with minimal delay.',
      'Built a bidirectional WebSocket architecture for persistent, low-latency real-time communication between client and server.',
      'Designed a responsive UI that dynamically updates transcripts without lag or unnecessary re-renders during live sessions.',
      'Enabled transcript editing, timestamp filtering, and export capabilities for practical usability.',
    ],
    engineering: [
      'Optimized WebSocket event handling to minimize latency in continuous speech processing pipelines.',
      'Designed efficient frontend rendering strategies to avoid UI bottlenecks during long transcription sessions.',
      'Structured backend message queues to support persistent streaming workflows reliably.',
    ],
    impact: [
      'Independently designed and implemented the complete system architecture from scratch.',
      'Focused heavily on low latency, synchronization, and real-time event handling correctness.',
    ],
    keywords: ['Real-Time Systems', 'WebSockets', 'Low Latency Architecture', 'Speech-to-Text', 'Frontend Optimization', 'Event-Driven Systems'],
  },

  {
    _id: 'smart-toolkit',
    slug: 'smart-toolkit-inspector',
    title: 'Smart Toolkit Inspector',
    subtitle: 'AI-Based Industrial Inspection System',
    tagline: 'Industrial computer vision system for automated toolkit inspection using depth sensing and real-time object detection.',
    category: 'Research',
    techStack: ['YOLOv11', 'Python', 'OpenCV', 'Intel RealSense SDK', 'Computer Vision', 'Depth Estimation', 'RGB-D Imaging'],
    metrics: [
      { label: 'Segmentation', value: '96.9%' },
      { label: 'Detection',    value: '93.2%' },
      { label: 'Published',    value: 'CMC Journal' },
      { label: 'Year',         value: '2025' },
    ],
    specialBadge: 'Published Research',
    demoUrl: '',
    githubUrl: '',
    paperUrl: 'https://www.techscience.com/cmc/v86n1/64475',
    built: [
      'Developed an AI-powered toolkit inspection system for automated identification and dimensional analysis of industrial tools.',
      'Used RGB-D imaging with Intel RealSense cameras to detect sockets and deep sockets in real time on an assembly line.',
      'Combined object detection and edge-based measurement pipelines for accurate, repeatable industrial measurements.',
    ],
    engineering: [
      'Optimized inference workflows to reduce real-time latency for industrial environments with strict throughput requirements.',
      'Designed lightweight processing pipelines to support edge deployment scenarios without cloud dependency.',
      'Improved measurement precision using depth + RGB fusion techniques for reliable dimensional analysis.',
    ],
    impact: [
      'Led development of detection workflows and production-focused implementation under real industrial constraints.',
      'Worked closely with industrial deployment requirements, ensuring reliability in noisy, high-throughput environments.',
      'Resulted in a peer-reviewed publication in Computers, Materials & Continua (CMC) — an international journal.',
    ],
    keywords: ['Computer Vision', 'YOLO', 'Edge AI', 'Industrial Automation', 'Depth Imaging', 'Real-Time Detection', 'AI Systems'],
  },

  {
    _id: 'sdnum',
    slug: 'sdnum',
    title: 'SDNUM',
    subtitle: 'Software Defined Underwater Monitoring & Routing Framework',
    tagline: 'Patent-backed SDN-based underwater routing and monitoring system for secure, adaptive communication in underwater acoustic sensor networks.',
    category: 'Research',
    specialBadge: 'Patent-backed',
    techStack: ['Python', 'Software Defined Networking (SDN)', 'Network Simulation', 'Routing Algorithms', 'Trust Models'],
    metrics: [
      { label: 'Recognition', value: 'Patent' },
      { label: 'Status',      value: 'Published' },
      { label: 'Country',     value: 'India' },
      { label: 'Year',        value: '2025' },
    ],
    demoUrl: '',
    githubUrl: '',
    paperUrl: '',
    built: [
      'Designed a software-defined underwater communication framework for adaptive and intelligent packet routing.',
      'Developed trust-aware routing mechanisms to improve network reliability and security in underwater acoustic sensor networks.',
      'Implemented dynamic monitoring and intelligent decision-making for packet routing across changing network topologies.',
    ],
    engineering: [
      'Introduced adaptive trust routing mechanisms to handle changing underwater network conditions without manual reconfiguration.',
      'Improved communication efficiency and network resilience in unstable underwater environments.',
      'Proposed a scalable architecture supporting future expansion of underwater monitoring infrastructure.',
    ],
    impact: [
      'Co-authored research and contributed to a published Indian patent (2025).',
      'Worked on both system architecture design and routing logic implementation.',
    ],
    keywords: ['Software Defined Networking', 'Distributed Systems', 'Network Security', 'Routing Algorithms', 'Research Engineering', 'System Architecture'],
  },
];
